package vistas;

import datos.RepuestoData;
import entidades.Repuesto;
import javax.swing.JOptionPane;

/**
 *
 * @author Grupo10
 */
public class Jf_Repuesto extends javax.swing.JFrame {

    private final java.awt.Frame padre;
    private Repuesto repuesto;
    private RepuestoData repuDa;

    public Jf_Repuesto(java.awt.Frame padre, Repuesto repuesto) {
        initComponents();
        this.padre = padre;
        this.repuesto = repuesto;
        this.repuDa = new RepuestoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTf_serie = new javax.swing.JTextField();
        jTf_descripcion = new javax.swing.JTextField();
        jTf_costo = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JLabel();
        btn_guardar1 = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTf_serie.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTf_serie.setBorder(null);
        jTf_serie.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTf_serieComponentShown(evt);
            }
        });
        jPanel1.add(jTf_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 270, 20));

        jTf_descripcion.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTf_descripcion.setBorder(null);
        jTf_descripcion.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTf_descripcionComponentShown(evt);
            }
        });
        jPanel1.add(jTf_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 270, 20));

        jTf_costo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTf_costo.setBorder(null);
        jTf_costo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTf_costoComponentShown(evt);
            }
        });
        jPanel1.add(jTf_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 270, 20));
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 120, 40));

        btn_guardar1.setBackground(new java.awt.Color(82, 148, 202));
        btn_guardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Btn-xGuarda.png"))); // NOI18N
        btn_guardar1.setBorder(null);
        btn_guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 140, 50));

        btn_salir.setBackground(new java.awt.Color(82, 148, 202));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Btn-xSalir.png"))); // NOI18N
        btn_salir.setBorder(null);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 140, 50));

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/repueBkg.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTf_serieComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTf_serieComponentShown
        jTf_serie.setOpaque(false);
    }//GEN-LAST:event_jTf_serieComponentShown

    private void jTf_descripcionComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTf_descripcionComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTf_descripcionComponentShown

    private void jTf_costoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTf_costoComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTf_costoComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.padre.setEnabled(false);
        if (repuesto != null) {
            jTf_serie.setText(String.valueOf(repuesto.getSerie()));
            jTf_descripcion.setText(repuesto.getDescripcion());
            jTf_costo.setText(String.valueOf(repuesto.getCosto()));
            jTf_serie.enable(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.padre.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void btn_guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar1ActionPerformed
            if (esNumero(jTf_serie.getText()) && esFloat(jTf_costo.getText()) && jTf_descripcion.getText().length() > 1) {
            if (repuesto == null) {
                repuesto = new Repuesto();
                repuesto.setSerie(Integer.parseInt(jTf_serie.getText()));
                repuesto.setDescripcion(jTf_descripcion.getText());
                repuesto.setCosto(Float.parseFloat(jTf_costo.getText()));
                repuesto.setEstado(true);
                repuDa.altaRepuesto(repuesto);
            } else {
                repuesto.setDescripcion(jTf_descripcion.getText());
                repuesto.setCosto(Float.parseFloat(jTf_costo.getText()));
                repuDa.modificacionRepuesto(repuesto);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe completar todos los datos correctamente");
        }
    }//GEN-LAST:event_btn_guardar1ActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.padre.setEnabled(true);
        this.dispose();       
    }//GEN-LAST:event_btn_salirActionPerformed

        public boolean esNumero(String cadena) {
        boolean resultado;
        try {
            Integer.parseInt(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }
        return resultado;
    }

    public boolean esFloat(String cadena) {
        boolean resultado;
        try {
            Float.parseFloat(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }
        return resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_guardar;
    private javax.swing.JButton btn_guardar1;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTf_costo;
    private javax.swing.JTextField jTf_descripcion;
    private javax.swing.JTextField jTf_serie;
    // End of variables declaration//GEN-END:variables
}
