/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Pat
 */
public class Jf_Servicio extends javax.swing.JFrame {

    private final java.awt.Frame padre;
    private boolean esNuevo;

    /**
     * Creates new form Jif_Cliente
     */
    public Jf_Servicio(java.awt.Frame padre, boolean esNuevo) {
        initComponents();
        this.padre = padre;
        this.esNuevo = esNuevo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTf_codServ = new javax.swing.JTextField();
        jTf_descrip = new javax.swing.JTextField();
        jTf_costo = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JLabel();
        btn_guardar1 = new javax.swing.JButton();
        btn_cambiar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTf_codServ.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTf_codServ.setBorder(null);
        jTf_codServ.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTf_codServComponentShown(evt);
            }
        });
        jPanel1.add(jTf_codServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 270, 20));

        jTf_descrip.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTf_descrip.setBorder(null);
        jTf_descrip.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTf_descripComponentShown(evt);
            }
        });
        jPanel1.add(jTf_descrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 270, 20));

        jTf_costo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTf_costo.setBorder(null);
        jTf_costo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTf_costoComponentShown(evt);
            }
        });
        jPanel1.add(jTf_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 270, 20));
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 120, 40));

        btn_guardar1.setText("GUARDAR");
        jPanel1.add(btn_guardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 130, 40));

        btn_cambiar.setText("CAMBIAR");
        jPanel1.add(btn_cambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 130, 40));

        btn_salir.setText("SALIR");
        jPanel1.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 130, 40));

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/servicioBkg.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTf_codServComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTf_codServComponentShown
        jTf_codServ.setOpaque(false);
    }//GEN-LAST:event_jTf_codServComponentShown

    private void jTf_descripComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTf_descripComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTf_descripComponentShown

    private void jTf_costoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTf_costoComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTf_costoComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.padre.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.padre.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cambiar;
    private javax.swing.JLabel btn_guardar;
    private javax.swing.JButton btn_guardar1;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTf_codServ;
    private javax.swing.JTextField jTf_costo;
    private javax.swing.JTextField jTf_descrip;
    // End of variables declaration//GEN-END:variables
}
